// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2zdbRekkysocFRfgXwdu7nrzHGkQVl7M',
    appId: '1:297658462947:web:109fb89d1b50c678bd4bd6',
    messagingSenderId: '297658462947',
    projectId: 'kitt-plus-ae423',
    authDomain: 'kitt-plus-ae423.firebaseapp.com',
    storageBucket: 'kitt-plus-ae423.appspot.com',
    measurementId: 'G-5GK7WTEKQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk6rhfY8piQ3RMMvB7hrmOS3Vd4wC4sgQ',
    appId: '1:297658462947:android:3c6a3892030b2bb5bd4bd6',
    messagingSenderId: '297658462947',
    projectId: 'kitt-plus-ae423',
    storageBucket: 'kitt-plus-ae423.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcp_-roCwwPdZZM06pjpNuW9jY_TkjV70',
    appId: '1:297658462947:ios:c172e10f95dc032ebd4bd6',
    messagingSenderId: '297658462947',
    projectId: 'kitt-plus-ae423',
    storageBucket: 'kitt-plus-ae423.appspot.com',
    iosClientId: '297658462947-vqen1acq17p8m9dfc31rghk5k521q5fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.kittPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcp_-roCwwPdZZM06pjpNuW9jY_TkjV70',
    appId: '1:297658462947:ios:c172e10f95dc032ebd4bd6',
    messagingSenderId: '297658462947',
    projectId: 'kitt-plus-ae423',
    storageBucket: 'kitt-plus-ae423.appspot.com',
    iosClientId: '297658462947-vqen1acq17p8m9dfc31rghk5k521q5fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.kittPlus',
  );
}
